### ISSUE TITLE
Commenting out lines with ctrl+/ not supported properly

### ISSUE THREAD

**Issue by grandixximo** [MX-Master/atom-language-linuxcnc-gcode#2]
If in atom i try to comment out with Ctrl+/ it should comment out lines one by one with the ;
instead it adds */ and /* that does not actually comment out the code

**Comment by MX-Master** [comment]
Fixed in the **v0.1.1**. Thanks for the report (:

Update the package in the Atom

**Comment by grandixximo** [comment]
I have another request if you would be so nice, you could make a different color for M2 and M30, it would be awesome since they are codes to terminate the program and not normal Modular codes.

**Comment by MX-Master** [comment]
it's not a trivial work, because single regex 

https://github.com/MX-Master/atom-language-linuxcnc-gcode/blob/master/grammars/linuxcnc-gcode.cson#L44-L47

must be replaced with two long lists of M codes
