### ISSUE TITLE
Gcode not hightlighting in Atom ?

### ISSUE THREAD

**Issue by questuk** [MX-Master/atom-language-linuxcnc-gcode#3]
Hi,

I have installed your addon, but if i select a 3d printer g code no colors are shown  on some ?
At the bottom of Atom is hows that it has recognized it as G code.

I enclose a working highlighting and non working versions of Gcode

[Gcode files.zip](https://github.com/MX-Master/atom-language-linuxcnc-gcode/files/2737518/Gcode.files.zip)

Thanks
Gaz

**Comment by MX-Master** [comment]
It's all about file size. The atom is editor for small files. Highlighting of large files is really slow (and buggy).

To test all I'm talking about:
- open file "**Does not work.gcode**" file
- cut half of a text (but don't save)
- change the highlighting type to **plain text**
- change the highlighting type again to **G-Code**
- and you will see a slow highlighting process
- then make UNDO to return all text back
- and you will see the atom trying to highlight this cut part of a text

It's not my fault. It's Atom (:
